version: "2"
services:
  mysql:
    image: mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password1
  
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password1
      MYSQL_HOST: mysql